#!/bin/bash

root=$(cd $(dirname "$0")/..; pwd -P)
target="$HOME"

source "$root"/scripts/functions.sh

os=$(detect-os)

symlink. bash_profile bash_profile_lib bashrc profile
symlink. ctags.d
symlink. gitignore gitconfig
symlink. ipython/profile_default/ipython_config.py
symlink. iterm2
symlink. stack/config.yaml
symlink. tmux
symlink. tmux.conf
symlink. touchmode
symlink. ttrc
symlink. vexrc
symlink. vim vimrc
symlink bin


# Find firefox profiles and add user config.
FIREFOX_PROFILE_ROOTS=(\
  .mozilla/firefox \
  "Library/Application Support/Firefox/Profiles" \
)

FIREFOX_PROFILE_NAMES=(\
  *.default \
  *.default-* \
)

for profile_root in "${FIREFOX_PROFILE_ROOTS[@]}"; do
  for profile_name in "${FIREFOX_PROFILE_NAMES[@]}"; do
    for profile in "$target/$profile_root"/$profile_name; do
      if [ -d "$profile" ]; then
        # NOTE: Firefox on MacOS refuses to load profile chrome if it's
        # symlinked :'( Rsync it in there, but symlink elsewhere
        if [ "$os" = "Darwin" ]; then
          rsync -r firefox/chrome "$profile"/
        else
          ln -sf "$root"/firefox/chrome "$profile"/
        fi
      fi
    done
  done
done
