#!/bin/bash

root=$(cd $(dirname "$0")/..; pwd -P)
target="$HOME"

source "$root/scripts/functions.sh"

os=$(detect-os)

symlink. bash_profile bash_profile_lib bashrc profile
symlink. config/i3
symlink. ctags.d
symlink. ghci
symlink. gitignore gitconfig
symlink. haskeline
symlink. inputrc
symlink. ipython/profile_default/ipython_config.py
symlink. iterm2
symlink. stack/config.yaml
symlink. tmux
symlink. tmux.conf
symlink. touchmode
symlink. ttrc
symlink. vexrc
symlink. vim vimrc
symlink bin

source "$root/scripts/bootstrap-firefox-profiles.sh"
