#!/bin/bash

root=$(cd $(dirname "$0")/..; pwd -P)
target="$HOME"

source "$root"/scripts/functions.sh

symlink. bash_profile bash_profile_lib
symlink. vim vimrc
symlink. gitignore gitconfig
symlink. vexrc
symlink. ctags
symlink. ipython/profile_default/ipython_config.py
symlink. stack/config.yaml
symlink bin
